/**
 * `tracegraph schema doctor`  — scan local artifacts for version mismatches.
 * `tracegraph baseline migrate` — migrate old baseline files to the current schema.
 *
 * Schema mismatch exits with code 5 (EXIT_CODES.SCHEMA_MIGRATION) so CI can
 * distinguish this failure from a test or findings failure.
 */
import fs   from 'fs';
import path from 'path';
import { EXIT_CODES, SCHEMA_VERSIONS } from '@tracegraph/shared-types';

// ─── schema doctor ────────────────────────────────────────────────────────────

export type SchemaDoctorOptions = {
  json?: boolean;
};

type ArtifactReport = {
  file:            string;
  kind:            'trace' | 'baseline' | 'report';
  foundVersion:    string | null;
  expectedVersion: string;
  status:          'ok' | 'mismatch' | 'unreadable';
};

/**
 * `tracegraph schema doctor`
 *
 * Scans .tracegraph/{traces,baselines,reports}/ and reports any files whose
 * schemaVersion does not match the current CLI expectations.
 *
 * Exit codes:
 *   0 — all artifacts are current
 *   5 — at least one artifact has a mismatched schema version
 */
export function schemaDoctorCommand(options: SchemaDoctorOptions): number {
  const cwd           = process.cwd();
  const tracegraphDir = path.join(cwd, '.tracegraph');

  if (!fs.existsSync(tracegraphDir)) {
    process.stdout.write('[tracegraph] No .tracegraph/ directory found — nothing to check.\n');
    return EXIT_CODES.SUCCESS;
  }

  const reports: ArtifactReport[] = [
    ...scanDir(path.join(tracegraphDir, 'traces'),    'trace',    SCHEMA_VERSIONS.trace),
    ...scanDir(path.join(tracegraphDir, 'baselines'), 'baseline', SCHEMA_VERSIONS.baseline),
    ...scanDir(path.join(tracegraphDir, 'reports'),   'report',   SCHEMA_VERSIONS.report),
  ];

  if (options.json) {
    process.stdout.write(JSON.stringify(reports, null, 2) + '\n');
    return reports.some((r) => r.status !== 'ok')
      ? EXIT_CODES.SCHEMA_MIGRATION
      : EXIT_CODES.SUCCESS;
  }

  const ok          = reports.filter((r) => r.status === 'ok');
  const mismatched  = reports.filter((r) => r.status === 'mismatch');
  const unreadable  = reports.filter((r) => r.status === 'unreadable');

  const LINE = '─'.repeat(56);
  process.stdout.write('\nTraceGraph Schema Doctor\n');
  process.stdout.write(LINE + '\n');
  process.stdout.write(`Total artifacts scanned: ${reports.length}\n`);
  process.stdout.write(`  ✓ Current:    ${ok.length}\n`);
  process.stdout.write(`  ✗ Mismatched: ${mismatched.length}\n`);
  if (unreadable.length > 0) {
    process.stdout.write(`  ⚠ Unreadable: ${unreadable.length}\n`);
  }

  if (mismatched.length === 0 && unreadable.length === 0) {
    process.stdout.write('\nAll artifacts are at the current schema version.\n');
    process.stdout.write(LINE + '\n\n');
    return EXIT_CODES.SUCCESS;
  }

  if (mismatched.length > 0) {
    process.stdout.write('\nMismatched artifacts:\n');
    for (const r of mismatched) {
      process.stdout.write(
        `  ${r.kind.padEnd(10)} ${path.basename(r.file)}\n` +
        `             found: ${r.foundVersion ?? '(none)'}\n` +
        `          expected: ${r.expectedVersion}\n`,
      );
    }
    process.stdout.write('\nRun the appropriate migration:\n');
    if (mismatched.some((r) => r.kind === 'baseline')) {
      process.stdout.write('  tracegraph baseline migrate\n');
    }
    if (mismatched.some((r) => r.kind === 'trace' || r.kind === 'report')) {
      process.stdout.write('  tracegraph clean --all-runs  (traces and reports are regenerated by re-running)\n');
    }
  }

  if (unreadable.length > 0) {
    process.stdout.write('\nUnreadable files (corrupt or empty):\n');
    for (const r of unreadable) {
      process.stdout.write(`  ${r.kind.padEnd(10)} ${path.basename(r.file)}\n`);
    }
  }

  process.stdout.write(LINE + '\n\n');
  return EXIT_CODES.SCHEMA_MIGRATION;
}

// ─── baseline migrate ─────────────────────────────────────────────────────────

export type BaselineMigrateOptions = {
  dryRun?: boolean;
};

/**
 * `tracegraph baseline migrate`
 *
 * Attempts to migrate baseline files to the current schema version.
 *
 * Current schema fields added between versions:
 *   v1 → v1: no structural change; some optional fields may be absent.
 *
 * For each baseline file that has a mismatched schemaVersion:
 *  - If the structure is compatible (same fields, just old version string):
 *    updates the schemaVersion field and re-serialises.
 *  - If the structure is incompatible: reports that manual reconstruction
 *    is required via `tracegraph baseline create`.
 *
 * Exits with code 5 if any baselines could not be migrated automatically.
 */
export function baselineMigrateCommand(options: BaselineMigrateOptions): number {
  const cwd          = process.cwd();
  const baselinesDir = path.join(cwd, '.tracegraph', 'baselines');

  if (!fs.existsSync(baselinesDir)) {
    process.stdout.write('[tracegraph] No baselines directory found — nothing to migrate.\n');
    return EXIT_CODES.SUCCESS;
  }

  const files = fs.readdirSync(baselinesDir)
    .filter((f) => f.endsWith('.baseline.json'))
    .map((f) => path.join(baselinesDir, f));

  if (files.length === 0) {
    process.stdout.write('[tracegraph] No baseline files found.\n');
    return EXIT_CODES.SUCCESS;
  }

  let migrated = 0;
  let skipped  = 0;
  let failed   = 0;

  for (const file of files) {
    let raw: Record<string, unknown>;
    try {
      raw = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
    } catch {
      process.stderr.write(`  [error] Cannot read ${path.basename(file)} — skipping.\n`);
      failed++;
      continue;
    }

    if (raw['schemaVersion'] === SCHEMA_VERSIONS.baseline) {
      skipped++;
      continue;
    }

    const oldVersion = raw['schemaVersion'] as string | undefined;

    // Apply field-level migration heuristics here as the schema evolves.
    // Currently v1 is the only version, so any mismatch is treated as
    // a best-effort version-string update (the shape hasn't changed).
    if (
      typeof raw['baselineId'] === 'string' &&
      typeof raw['testId']     === 'string' &&
      Array.isArray(raw['events'])
    ) {
      raw['schemaVersion'] = SCHEMA_VERSIONS.baseline;

      if (options.dryRun) {
        process.stdout.write(
          `  [dry-run] Would migrate ${path.basename(file)}: ${oldVersion ?? '(none)'} → ${SCHEMA_VERSIONS.baseline}\n`,
        );
      } else {
        fs.writeFileSync(file, JSON.stringify(raw, null, 2) + '\n', 'utf8');
        process.stdout.write(
          `  [ok] Migrated ${path.basename(file)}: ${oldVersion ?? '(none)'} → ${SCHEMA_VERSIONS.baseline}\n`,
        );
      }
      migrated++;
    } else {
      process.stderr.write(
        `  [warn] ${path.basename(file)} schema is incompatible — cannot auto-migrate.\n` +
        `         Regenerate with: tracegraph baseline create --all-traces\n`,
      );
      failed++;
    }
  }

  process.stdout.write(
    `\n[tracegraph] baseline migrate: ${migrated} migrated, ${skipped} already current, ${failed} failed.\n`,
  );

  return failed > 0 ? EXIT_CODES.SCHEMA_MIGRATION : EXIT_CODES.SUCCESS;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function scanDir(
  dir:             string,
  kind:            ArtifactReport['kind'],
  expectedVersion: string,
): ArtifactReport[] {
  if (!fs.existsSync(dir)) return [];

  const ext = kind === 'trace'    ? '.trace.json'
            : kind === 'baseline' ? '.baseline.json'
            : '.report.json';

  return fs.readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .map((f): ArtifactReport => {
      const file = path.join(dir, f);
      try {
        const data = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
        const foundVersion = (data['schemaVersion'] as string | undefined) ?? null;
        return {
          file,
          kind,
          foundVersion,
          expectedVersion,
          status: foundVersion === expectedVersion ? 'ok' : 'mismatch',
        };
      } catch {
        return { file, kind, foundVersion: null, expectedVersion, status: 'unreadable' };
      }
    });
}
