/**
 * G1 — Graphify runner
 *
 * Detects Graphify installation and executes it as a Python subprocess.
 * Copies the output files (graph.json, graph.html, GRAPH_REPORT.md) to
 * .tracegraph/static-graph/graphify/ after a successful run.
 *
 * The build command is fully configurable via staticGraph.buildCommand.
 * Default: "graphify . --directed"
 *
 * Auto-retry behaviour:
 *   If Graphify exits with "no LLM API key found", the repo contains non-code
 *   files (docs, images, PDFs) that require a backend for semantic extraction.
 *   We automatically retry with a temporary .graphifyignore that restricts
 *   analysis to code files only — no API key needed for that corpus.
 */
import * as fs           from 'fs';
import * as path         from 'path';
import { spawnSync }     from 'child_process';
import { graphifyDir, rawGraphPath, GRAPHIFY_GITIGNORE_CONTENT } from './graph-dir';

// ─── Detection ───────────────────────────────────────────────────────────────

export type GraphifyDetection = {
  found:   boolean;
  version: string | null;
  /** The command that worked (e.g. "graphify --version"). */
  cmd:     string[] | null;
};

/**
 * Detect a working Graphify installation.
 *
 * graphifyy is installed into an isolated environment by uv/pipx, so
 * `python -m graphify` will never resolve — only the `graphify` binary
 * placed on PATH by the installer works.
 */
export function detectGraphify(): GraphifyDetection {
  try {
    const result = spawnSync('graphify', ['--version'], {
      encoding: 'utf8',
      stdio:    'pipe',
      timeout:  8_000,
      shell:    process.platform === 'win32',
    });
    if (result.status === 0) {
      const version = parseVersion(result.stdout ?? result.stderr ?? '');
      return { found: true, version, cmd: ['graphify', '--version'] };
    }
  } catch { /* not in PATH */ }

  return { found: false, version: null, cmd: null };
}

/** Parse a version string like "graphify 0.4.1" → "0.4.1" */
function parseVersion(output: string): string | null {
  const m = output.match(/(\d+\.\d+(?:\.\d+)?)/);
  return m ? m[1]! : output.trim().split('\n')[0] ?? null;
}

// ─── Code-only .graphifyignore ────────────────────────────────────────────────

/**
 * Written as a temporary .graphifyignore when Graphify reports that non-code
 * files need an LLM API key. Excludes all doc/image/media types so the retry
 * run processes only source code (which tree-sitter handles locally, no key).
 */
/**
 * Graphify classifies four categories as "doc/paper/image" requiring an LLM backend:
 *   Docs   → Markdown, HTML, YAML, plain text, RST
 *   Papers → PDF
 *   Images → PNG, JPG, WEBP, GIF, SVG, ICO …
 *   Other  → Office docs, XML, template files (EJS, Pug, HBS …)
 *
 * Everything in this list is excluded so the retry run processes code only.
 * Tree-sitter handles code extraction locally — no API key required.
 */
const CODE_ONLY_GRAPHIFYIGNORE = `# Auto-generated by TraceGraph — code-only mode (no LLM API key available).
# Excludes all doc/image/template file types so Graphify can run without a backend.
# Delete this file and set ANTHROPIC_API_KEY (or GEMINI_API_KEY etc.) to include docs.

# ── Docs / text (Graphify sends these to an LLM backend) ──────────────────────
*.md
*.markdown
*.txt
*.rst
*.adoc
*.asciidoc

# ── HTML & templates (treated as docs by Graphify) ────────────────────────────
*.html
*.htm
*.xhtml
*.ejs
*.pug
*.jade
*.hbs
*.handlebars
*.mustache
*.njk
*.jinja
*.jinja2
*.twig

# ── YAML / XML (Graphify docs category) ──────────────────────────────────────
*.yaml
*.yml
*.xml
*.svg

# ── Stylesheets (not code, not needed for architecture graph) ─────────────────
*.css
*.scss
*.sass
*.less
*.styl

# ── PDFs and office docs ──────────────────────────────────────────────────────
*.pdf
*.docx
*.pptx
*.xlsx
*.odt
*.ods
*.odp
*.pages
*.numbers
*.key
*.epub

# ── Images ───────────────────────────────────────────────────────────────────
*.png
*.jpg
*.jpeg
*.gif
*.webp
*.ico
*.bmp
*.tiff
*.tif
*.avif
*.heic
*.heif
*.eps
*.psd
*.ai

# ── Audio / video ─────────────────────────────────────────────────────────────
*.mp4
*.mp3
*.wav
*.mov
*.avi
*.mkv
*.webm
*.ogg
*.flac
*.m4a
*.m4v

# ── Common non-code directories ───────────────────────────────────────────────
docs/
documentation/
doc/
papers/
assets/
images/
media/
static/
public/css/
public/images/
.github/
`.trimStart();

/** Error substring emitted by Graphify when non-code files need an API key. */
const NO_API_KEY_MARKER = 'no LLM API key found';
/**
 * Error substring emitted by Graphify when a backend-specific Python package
 * (e.g. `openai`, `anthropic`) is present in the environment as an API key
 * but the matching SDK is not installed in the Graphify venv.
 *
 * Example: OPENAI_API_KEY is set, Graphify selects the OpenAI backend, but
 * `pip install openai` was never run inside the Graphify tool environment.
 *
 * Fix: `uv tool install "graphifyy[openai]" --force`
 * TraceGraph response: same as NO_API_KEY_MARKER — auto-retry in code-only mode.
 */
const MISSING_BACKEND_PACKAGE_MARKER = 'package is required for this backend but is not installed';

// ─── Runner ──────────────────────────────────────────────────────────────────

export type RunGraphifyResult =
  | { ok: true;  graphJsonPath: string; codeOnly?: boolean }
  | { ok: false; error: string };

/**
 * Run Graphify in `projectDir` and copy its output to `.tracegraph/static-graph/graphify/`.
 *
 * Auto-retry behaviour: if the first run fails because non-code files require
 * an LLM backend (either no API key is set, or the backend's Python package is
 * not installed in the Graphify venv), a temporary `.graphifyignore` is written
 * to exclude those files and the run is retried automatically.  The
 * `.graphifyignore` is removed after the retry so subsequent `graphify --update`
 * calls still work as expected.
 *
 * @param projectDir   The project root to analyse.
 * @param buildCommand The configured build command (default: "graphify . --directed").
 * @param timeoutMs    Maximum execution time in milliseconds (default: 300s).
 * @param onProgress   Optional progress callback for streaming status lines.
 */
export function runGraphify(
  projectDir: string,
  buildCommand: string,
  timeoutMs = 300_000,
  onProgress?: (line: string) => void,
): RunGraphifyResult {
  onProgress?.(`[tracegraph] Running: ${buildCommand}`);

  // ── Split build command into argv ─────────────────────────────────────────
  const parts = splitCommand(buildCommand);
  if (parts.length === 0) {
    return { ok: false, error: 'buildCommand is empty' };
  }

  const spawnOpts = {
    cwd:     projectDir,
    encoding: 'utf8' as const,
    stdio:    'pipe'  as const,
    timeout:  timeoutMs,
    shell:    process.platform === 'win32',
  };

  // ── First attempt ─────────────────────────────────────────────────────────
  let result = spawnSync(parts[0]!, parts.slice(1), spawnOpts);

  if (result.error) {
    return { ok: false, error: `Process error: ${String(result.error)}` };
  }

  // ── Auto-retry: code-only mode ────────────────────────────────────────────
  let codeOnly    = false;
  let firstOutput = '';          // saved to compose an accurate final note
  if (result.status !== 0) {
    const output = ((result.stderr ?? '') + (result.stdout ?? '')).trim();
    firstOutput  = output;

    const noKey         = output.includes(NO_API_KEY_MARKER);
    const missingPkg    = output.includes(MISSING_BACKEND_PACKAGE_MARKER);

    if (noKey || missingPkg) {
      // Non-code files need an LLM backend that is either unconfigured (no API
      // key) or whose SDK is not installed in the Graphify venv — retry
      // excluding those files so tree-sitter handles code files locally.
      const reason = missingPkg
        ? '[tracegraph] LLM backend package not installed — retrying in code-only mode.'
        : '[tracegraph] Non-code files detected — retrying in code-only mode (no API key needed).';
      onProgress?.(reason);

      // ── Write temp .graphifyignore ───────────────────────────────────────
      const ignorePath        = path.join(projectDir, '.graphifyignore');
      const hadExistingIgnore = fs.existsSync(ignorePath);
      if (!hadExistingIgnore) {
        fs.writeFileSync(ignorePath, CODE_ONLY_GRAPHIFYIGNORE, 'utf8');
      }

      // ── Clear graphify-out/ cache ────────────────────────────────────────
      // The first (failed) run already populated graphify-out/ with a SHA256
      // file cache that lists the doc files we want to exclude.  If we don't
      // clear it, graphify reads the cached file list on the retry and still
      // tries to extract the same doc files — ignoring the new .graphifyignore.
      const graphifyOutDir = path.join(projectDir, 'graphify-out');
      if (fs.existsSync(graphifyOutDir)) {
        try { fs.rmSync(graphifyOutDir, { recursive: true, force: true }); } catch { /* non-fatal */ }
      }

      // ── Retry with --force to guarantee a full rescan ────────────────────
      const retryParts = [...parts];
      if (!retryParts.includes('--force')) retryParts.push('--force');
      result = spawnSync(retryParts[0]!, retryParts.slice(1), spawnOpts);

      // ── Restore state ────────────────────────────────────────────────────
      // Remove the temp .graphifyignore so future --update runs are unaffected.
      if (!hadExistingIgnore) {
        try { fs.unlinkSync(ignorePath); } catch { /* non-fatal */ }
      }

      codeOnly = true;
    }
  }

  // ── Check final result ────────────────────────────────────────────────────
  if (result.status !== 0) {
    const stderr = (result.stderr ?? '').trim();
    const stdout = (result.stdout ?? '').trim();
    return {
      ok:    false,
      error: `Graphify exited with code ${result.status ?? '?'}.\n${stderr || stdout}`,
    };
  }

  // ── Ensure output directory exists ────────────────────────────────────────
  const outDir = graphifyDir(projectDir);
  fs.mkdirSync(outDir, { recursive: true });

  // ── Write .gitignore inside our output dir ────────────────────────────────
  const gitignorePath = path.join(outDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, GRAPHIFY_GITIGNORE_CONTENT, 'utf8');
  }

  // ── Locate and copy output files ──────────────────────────────────────────
  const graphJsonPath = locateAndCopyOutput(projectDir, outDir, 'graph.json', onProgress);

  if (!graphJsonPath) {
    return {
      ok:    false,
      error: `Graphify ran but graph.json was not found.\n` +
             `Check the buildCommand output or set staticGraph.buildCommand to a path ` +
             `that writes graph.json into the project directory.`,
    };
  }

  // Also copy graph.html and GRAPH_REPORT.md if present
  locateAndCopyOutput(projectDir, outDir, 'graph.html', onProgress);
  locateAndCopyOutput(projectDir, outDir, 'GRAPH_REPORT.md', onProgress);

  if (codeOnly) {
    if (firstOutput.includes(MISSING_BACKEND_PACKAGE_MARKER)) {
      onProgress?.(
        '[tracegraph] Note: graph built from code files only.\n' +
        '  The LLM backend SDK is not installed in your Graphify environment.\n' +
        '  To include docs/non-code files, reinstall Graphify with the required extra, e.g.:\n' +
        '    uv tool install "graphifyy[openai]" --force\n' +
        '    uv tool install "graphifyy[anthropic]" --force',
      );
    } else {
      onProgress?.('[tracegraph] Note: graph built from code files only (set an API key env var to include docs).');
    }
  }
  onProgress?.(`[tracegraph] Static graph written to: ${outDir}`);
  return { ok: true, graphJsonPath, codeOnly };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Split a command string into argv array.
 * Handles quoted strings: `graphify . --output "my dir"` → ['graphify', '.', '--output', 'my dir']
 */
function splitCommand(cmd: string): string[] {
  const parts: string[] = [];
  let current           = '';
  let inQuote: '"' | "'" | null = null;

  for (const ch of cmd) {
    if (inQuote) {
      if (ch === inQuote) { inQuote = null; }
      else { current += ch; }
    } else if (ch === '"' || ch === "'") {
      inQuote = ch;
    } else if (ch === ' ') {
      if (current) { parts.push(current); current = ''; }
    } else {
      current += ch;
    }
  }
  if (current) parts.push(current);
  return parts;
}

/**
 * Locate `filename` produced by Graphify and copy it to `outDir`.
 *
 * We copy (not move) so that Graphify's `graphify-out/` directory is left
 * intact. Graphify uses that directory as a SHA256-based cache for
 * `--update` incremental rebuilds — deleting files there would force a full
 * re-extraction on every run.
 *
 * Returns the destination path on success, null if the file is not found.
 */
function locateAndCopyOutput(
  projectDir: string,
  outDir: string,
  filename: string,
  onProgress?: (line: string) => void,
): string | null {
  const candidates = [
    // Real Graphify (graphifyy on PyPI) writes to graphify-out/
    path.join(projectDir, 'graphify-out', filename),
    // Legacy / alternative output paths
    path.join(projectDir, filename),
    path.join(projectDir, 'graphify-output', filename),
    path.join(projectDir, '.graphify', filename),
  ];

  for (const src of candidates) {
    if (fs.existsSync(src)) {
      const dest = path.join(outDir, filename);
      // Copy only — do NOT delete the source. graphify-out/ is Graphify's
      // own cache directory and must remain intact for --update to work.
      if (path.resolve(src) !== path.resolve(dest)) {
        fs.copyFileSync(src, dest);
      }
      onProgress?.(`[tracegraph]   ${filename} → ${dest}`);
      return dest;
    }
  }

  // If the file is already in outDir (build command wrote there directly), accept it.
  const alreadyThere = path.join(outDir, filename);
  if (fs.existsSync(alreadyThere)) return alreadyThere;

  return null;
}

/** True if graph.json exists in the graphify output directory. */
export function graphJsonExists(projectDir: string): boolean {
  return fs.existsSync(rawGraphPath(projectDir));
}
