/**
 * M7A T7A.3 — prompt-pack unit tests
 *
 * Tests buildPromptPacks() for:
 *  - Returns one pack per requested format
 *  - Cursor format contains findings and correct fileName
 *  - Claude Code format produces valid XML-like structure
 *  - Copilot format starts with correct header and contains findings
 *  - MCP format is valid JSON with `resources` array
 *  - Empty findings → "No open findings" placeholder
 *  - Approved/suppressed findings are excluded from each pack
 *  - projectName appears in pack headers
 *  - All four formats generated by default
 */

import { describe, it, expect } from 'vitest';
import type { EvaluatedFinding, TraceReport } from '@tracegraph/shared-types';
import { buildPromptPacks } from '../src/prompt-pack';

// ─── Factory helpers ──────────────────────────────────────────────────────────

function makeFinding(overrides: Partial<EvaluatedFinding> = {}): EvaluatedFinding {
  return {
    id:          'find_001',
    fingerprint: 'abcd1234',
    ruleId:      'security.authorization.middleware_removed',
    severity:    'critical',
    category:    'security_authorization',
    title:       'Auth middleware removed',
    description: 'Authentication middleware was removed from the route.',
    evidence:    [],
    recommendation: 'Re-add the authentication middleware.',
    status:      'open',
    ...overrides,
  };
}

function makeReport(findings: EvaluatedFinding[] = []): TraceReport {
  return {
    schemaVersion: 'tracegraph.report.v1',
    reportId:      'rep_001',
    createdAt:     Date.now(),
    baselineDir:   '.tracegraph/baselines',
    candidateFiles: [],
    diffs:         [],
    findings,
    summary: {
      tracesCompared:       1,
      findingsBySeverity:   { info: 0, low: 0, medium: 0, high: 0, critical: 1 },
      hasOpenCritical:      true,
      suppressionsModified: false,
    },
  };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('buildPromptPacks() — format selection', () => {
  it('returns 4 packs by default', () => {
    const packs = buildPromptPacks({ report: makeReport() });
    expect(packs).toHaveLength(4);
  });

  it('returns only requested formats', () => {
    const packs = buildPromptPacks({
      report:  makeReport(),
      formats: ['cursor', 'mcp'],
    });
    expect(packs).toHaveLength(2);
    expect(packs.map(p => p.format)).toEqual(['cursor', 'mcp']);
  });

  it('each pack has the requested format', () => {
    const packs = buildPromptPacks({
      report:  makeReport(),
      formats: ['claude-code'],
    });
    expect(packs[0]?.format).toBe('claude-code');
  });
});

describe('buildPromptPacks() — cursor format', () => {
  it('has correct fileName', () => {
    const [pack] = buildPromptPacks({ formats: ['cursor'] });
    expect(pack?.fileName).toBe('.cursor/tracegraph-context.md');
  });

  it('contains the project name in the header', () => {
    const [pack] = buildPromptPacks({
      formats:     ['cursor'],
      projectName: 'my-invoice-api',
    });
    expect(pack?.content).toContain('my-invoice-api');
  });

  it('includes finding title and ruleId', () => {
    const [pack] = buildPromptPacks({
      formats: ['cursor'],
      report:  makeReport([makeFinding()]),
    });
    expect(pack?.content).toContain('Auth middleware removed');
    expect(pack?.content).toContain('security.authorization.middleware_removed');
  });

  it('shows "No open findings" when no findings', () => {
    const [pack] = buildPromptPacks({
      formats: ['cursor'],
      report:  makeReport([]),
    });
    expect(pack?.content).toContain('No open findings');
  });
});

describe('buildPromptPacks() — claude-code format', () => {
  it('has correct fileName', () => {
    const [pack] = buildPromptPacks({ formats: ['claude-code'] });
    expect(pack?.fileName).toBe('CLAUDE.md');
  });

  it('wraps content in <tracegraph_context>', () => {
    const [pack] = buildPromptPacks({
      formats: ['claude-code'],
      report:  makeReport([makeFinding()]),
    });
    expect(pack?.content).toContain('<tracegraph_context>');
    expect(pack?.content).toContain('</tracegraph_context>');
  });

  it('contains <findings> block', () => {
    const [pack] = buildPromptPacks({
      formats: ['claude-code'],
      report:  makeReport([makeFinding()]),
    });
    expect(pack?.content).toContain('<findings>');
    expect(pack?.content).toContain('</findings>');
  });

  it('escapes XML special characters in titles', () => {
    const [pack] = buildPromptPacks({
      formats: ['claude-code'],
      report:  makeReport([makeFinding({ title: 'Foo <bar> & "baz"' })]),
    });
    expect(pack?.content).toContain('Foo &lt;bar&gt; &amp; &quot;baz&quot;');
  });

  it('emits <!-- No open findings --> comment when no findings', () => {
    const [pack] = buildPromptPacks({
      formats: ['claude-code'],
      report:  makeReport([]),
    });
    expect(pack?.content).toContain('<!-- No open findings -->');
  });
});

describe('buildPromptPacks() — copilot format', () => {
  it('has correct fileName', () => {
    const [pack] = buildPromptPacks({ formats: ['copilot'] });
    expect(pack?.fileName).toBe('.github/copilot-instructions.md');
  });

  it('starts with a markdown header containing project name', () => {
    const [pack] = buildPromptPacks({
      formats:     ['copilot'],
      projectName: 'cool-project',
    });
    expect(pack?.content).toMatch(/^# Copilot Instructions — cool-project/);
  });

  it('includes finding title and severity', () => {
    const [pack] = buildPromptPacks({
      formats: ['copilot'],
      report:  makeReport([makeFinding()]),
    });
    expect(pack?.content).toContain('Auth middleware removed');
    expect(pack?.content).toContain('critical');
  });

  it('shows "No open findings" when report is empty', () => {
    const [pack] = buildPromptPacks({
      formats: ['copilot'],
      report:  makeReport([]),
    });
    expect(pack?.content).toContain('No open findings');
  });
});

describe('buildPromptPacks() — mcp format', () => {
  it('has correct fileName', () => {
    const [pack] = buildPromptPacks({ formats: ['mcp'] });
    expect(pack?.fileName).toBe('.tracegraph/mcp-context.json');
  });

  it('produces valid JSON', () => {
    const [pack] = buildPromptPacks({
      formats: ['mcp'],
      report:  makeReport([makeFinding()]),
    });
    expect(() => JSON.parse(pack?.content ?? '')).not.toThrow();
  });

  it('JSON has a resources array', () => {
    const [pack] = buildPromptPacks({ formats: ['mcp'] });
    const parsed = JSON.parse(pack?.content ?? '{}') as { resources: unknown[] };
    expect(Array.isArray(parsed.resources)).toBe(true);
  });

  it('findings resource has uri tracegraph://findings', () => {
    const [pack] = buildPromptPacks({
      formats: ['mcp'],
      report:  makeReport([makeFinding()]),
    });
    const parsed = JSON.parse(pack?.content ?? '{}') as {
      resources: Array<{ uri: string }>;
    };
    expect(parsed.resources.some(r => r.uri === 'tracegraph://findings')).toBe(true);
  });

  it('findings text mentions the finding title', () => {
    const [pack] = buildPromptPacks({
      formats: ['mcp'],
      report:  makeReport([makeFinding()]),
    });
    const parsed = JSON.parse(pack?.content ?? '{}') as {
      resources: Array<{ uri: string; text: string }>;
    };
    const findingsRes = parsed.resources.find(r => r.uri === 'tracegraph://findings');
    expect(findingsRes?.text).toContain('Auth middleware removed');
  });
});

describe('buildPromptPacks() — finding status filtering', () => {
  it('excludes suppressed findings from all formats', () => {
    const findings = [
      makeFinding({ status: 'open',       title: 'OpenFinding' }),
      makeFinding({ id: 'f2', status: 'suppressed', title: 'SuppressedFinding' }),
    ];
    const packs = buildPromptPacks({ report: makeReport(findings) });

    for (const pack of packs) {
      expect(pack.content).not.toContain('SuppressedFinding');
    }
  });

  it('excludes approved findings from all formats', () => {
    const findings = [
      makeFinding({ status: 'open',     title: 'OpenFinding' }),
      makeFinding({ id: 'f3', status: 'approved',  title: 'ApprovedFinding' }),
    ];
    const packs = buildPromptPacks({ report: makeReport(findings) });

    for (const pack of packs) {
      expect(pack.content).not.toContain('ApprovedFinding');
    }
  });
});

describe('buildPromptPacks() — no report', () => {
  it('returns packs with empty findings when no report supplied', () => {
    const packs = buildPromptPacks({ formats: ['cursor'] });
    expect(packs[0]?.content).toContain('No open findings');
  });
});
